---
output:
  pdf_document: default
  html_document: default
---
---

# Projeto - Data Science Academy

### André Campos da Silva
### 10 de Novembro, 2020

## Projeto  -  Analise de Sentimentos
Fazer uma analise de sentimentos no Twitter sobre as eleições dos USA.

## Coletando os dados

``` {r}
# Carrego os pacotes necessários para o projeto
#install.packages("twitteR")
#install.packages("ROAuth")
#install.packages('tm')
#install.packages("syuzhet")
#install.packages("wordcloud")

library('wordcloud')
library("twitteR")
library("ROAuth")
library("tm")
library("syuzhet")
library('tidyverse')
```

```{r}
# Criar as chaves e faço a conexão para o Twitter
api_key <- 'xxxxxxxxxxxxxxxxxxxxxxxx'
api_key_secret <- 'xxxxxxxxxxxxxxxxxxxxxxxx'
access_token <-'xxxxxxxxxxxxxxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxx'
access_token_secret <-'xxxxxxxxxxxxxxxxxxxxxxxx'
```

```{r}
setup_twitter_oauth(consumer_key = api_key, consumer_secret = api_key_secret,
                    access_token = access_token, access_secret = access_token_secret)
```


## Tratamento dos dados

```{r}
# Extraio 500 twitters em ingles com a #Joe Biden a intenção de verificar o que as pessoas 
# estão falando a respeito dele e da sua vitoria na eleição. 

twtters <- searchTwitter('#Joe Biden', n = 500, lang = 'en')
electionUSA <- twListToDF(twtters)
head(electionUSA)

# Tiro só o que interessa que são os textos
electionUSA_text <- electionUSA$text
head(electionUSA_text)
```

```{r}
# Faço o tratamento retirandos os caracteres e colocando tudo em minusculo.

# colocando em minusculo
electionUSA_text <- tolower(electionUSA_text)

# retirando os espações e brancos ('rt')
electionUSA_text <- gsub('rt', '', electionUSA_text)

# retirando os @ do indetificado do usuario
electionUSA_text <- gsub('@\\w+','',electionUSA_text)

# retirando pontuações
electionUSA_text <- gsub('[[:punct:]]','',electionUSA_text)

# retirando links nos textos
electionUSA_text <- gsub('http\\w+','',electionUSA_text)

# retirando os tabs dos textos
electionUSA_text <- gsub('[ |\t]{2,}','',electionUSA_text)

# retirando espaços em brancos no inicio
electionUSA_text <- gsub(' ^','',electionUSA_text)

# retirando espaços me branco no final
electionUSA_text <- gsub(' $','',electionUSA_text)

# retirando os emotions dos textos
electionUSA_text <- gsub("[^\x01-\x7F]", "", electionUSA_text)

head(electionUSA_text)
```

```{r}
# Como o R trabalha com processamento em linguagem natural converto o vetor 
# para o formato corpus.

corpus <- Corpus(VectorSource(electionUSA_text))
class(corpus)

electionUSA_corpus <- tm_map(corpus, function(x) removeWords(x, stopwords()))
```

```{r}
# Grafico para mostrar as palavras mais usadas nos twitters

wordcloud(electionUSA_corpus, min.freq = 10, colors = brewer.pal(8,'Dark2'),
          random.color = TRUE, max.words = 1000)

```

```{r}
# analyse de sentimentos, do pacote syuzhet
sentiment_election <- get_nrc_sentiment((electionUSA_text))

# Calcula o score para cada sentimento analisado e joga para um data frame.
sentiment_election_score <- data.frame(colSums(sentiment_election[,]))

# Atribuo um nome score para a soma dos scores de sentimentos.
names(sentiment_election_score) <- 'Score'
```

```{r}
# Crio uma outra coluna com o nome sentiment pegando os nomes dos sentimentos pela função row.names
# ficando assim com uma coluna para o sentimento e outra para a sua quantidade.
sentiment_election_score <- cbind('sentiment' = row.names(sentiment_election_score),sentiment_election_score)

# Como criei a coluna sentimento retiro os nomes das linhas com os sentimentos
rownames(sentiment_election_score) <- NULL
head(sentiment_election_score)

```
```{r}
# Grafico de barra mostrando os sentimentos.
sentiment_election_score %>%
ggplot(aes(x = sentiment, y = Score, fill = sentiment)) + 
  geom_bar(stat = "identity")+
  labs(x = 'Sentimento', y = 'Quantidade', 
       title = 'Analise de sentimento eleição USA - Vitoria do Joe Biden',
       fill  = 'Sentimentos')
```
